use_frameworks!

target 'WTLibrary-iOS-ObjC_Example' do
  pod 'WTLibrary-iOS-ObjC', :path => '../'

  target 'WTLibrary-iOS-ObjC_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
